### ISSUE TITLE
Servo Ports 35 and 36 do not recognize "0" as turn-off-power as do all the other servo ports.

### ISSUE THREAD

**Issue by EmbeddedMan** [Engineering-3/RCMx1#2]

**Comment by EmbeddedMan** [comment]
![image](https://user-images.githubusercontent.com/450056/59982289-65342680-95d5-11e9-92ba-85df19b573da.png)

I have been unable to reproduce this problem so far. This image shows all 8 servo outputs in their default bootup state (outputting 1.5ms pulses). I then execute the following PicoC program, which writes 0x00s to each of the servos, and then all of the outputs turn off.

writei2c(0x1C, 0x31, 0x00);
writei2c(0x1C, 0x32, 0x00);
writei2c(0x1C, 0x33, 0x00);
writei2c(0x1C, 0x34, 0x00);
writei2c(0x1C, 0x35, 0x00);
writei2c(0x1C, 0x36, 0x00);
writei2c(0x1C, 0x37, 0x00);
writei2c(0x1C, 0x38, 0x00);
exit(1);

**Comment by EmbeddedMan** [comment]
Does this problem only happen when there are other sequences of I2C data sent to the RCMx1 first? @E3t1jump

**Comment by E3t1jump** [comment]
I moved a different servo to Port 35 and it worked with 0x00 as power off. I'm now suspecting it is the two servos (maybe a different model). I will swap these for some others I have and report back.

**Comment by E3t1jump** [comment]
Confirmed; it is something up with the servos and not the RCMx1. Two new servos work as expected.
